services:
  test-db:
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: casbin_rule
    restart: always

  test:
    build: .
    container_name: adapter-testing
    volumes:
      - .:/casbin-tortoise
    depends_on:
      - test-db
